var appTableV1 = {
    ugtk: "HBB",
    g7A: "Post kodi",
    g7B: "BYD roʼy.sana",
    g7C: "BYD №",
    g7Ag7Bg7C: "BYD raqami",
    g1A: "Rejim nomi",
    g1B: "Rejim kodi",
    g1Ag1B: "Rejim",
    g32: "Tov. №",
    g37B: "Avv.rej. kodi",
    g37C: "Olib o‘t. xus.",
    g2Name: "Eksportchi/Jo‘natuvchi",
    g8Code2: "STIR/JSHSHIR",
    g33: "TIF TN kodi",
    g31NameNoIcon: "Yuk joylari va tovar tavsifi",
    g31Name: "Yuk joylari va tovar tavsifi"+
            "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(1)'><i class=\"fa fa-angle-double-down m-2 openerTextArea \"/></span>" +
            "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(0)'><i class=\"fa fa-angle-double-up m-2 openerTextArea \"/></span>",
    g15: "Jo‘n. mam.",
    g11: "Sav.qil. mam.",
    vidKontrakta: "Kont. mavj.",
    g34: "Kel.chiq.m. (34-gr)",
    s34: "Kel.chiq.m (31-gr)",
    g25: "Chegar. tr.",
    g20A: "Etk.ber. shart.kodi",
    g20B: "Etk.ber. shart.nomi",
    g20Name: "Etk.ber. manzili",
    g20Ag20B:"Yet.ber. sharti",
    g22A: "Val.",
    g45: "Boj. qiy.",
    g45Usd: "Boj. qiy.$",
    g42: "Fakt. qiy.",
    g42Usd: "Fakt. qiy.$",
    indxusd: "Boj.qiy. indeksi $",
    indxusdLn: "Boj.qiy. indeksi $",
    g45Usded: "Boj.qiy. 1 bir.$",
    g45UsdedLn: "Boj.qiy. 1 bir.$",
    g31Marka: "Tov. markasi",
    g35: "Brutto (kg)",
    g38: "Netto (kg)",
    g41: "Qo‘sh.o‘lch. bir.",
    g43: "O‘z.eht. (43-gr)",
    g31Amount: "Miqdor (31-gr)",
    vesEd: "1 bir. vazni",
    gdvipdate: "Rasm-n sana",
    gc3Date: "Olib kir.sana",
    metod: "Boj.qiy. usul",
    vzaimosvyaz: "O'zaro bog'l.",
    idn: "Shart. idn.№",
    obl: "To'l. tor.",
    lgot20: "Boj imtiyozi",
    lgot27: "Aksiz imtiyozi",
    lgot29: "QQS imtiyozi",
    sovstavka: "Um. stav.",
    asosQiymat: "Boj.qiym. asosi",
    ktd: "Tuz. (KTD)",
    oblYes: "xa",
    oblNo: "yo'q",
    methodText: "usul",
    all : "Xammasi"
};

var appTableV2 = {
    locationNm: "Tarkibiy tuzulma",
    g33:"TIF TN kodi",
    userNm:"Xodim",
    keyword:"Ishlatilgan kalit so'zi",
    resultTime:"O'rtacha vaqt sarfi",
    resultCount:"Topilgan qaydlar soni",
    insTime:"Izlash vaqti",
    all : "Xammasi"
};

var appTableV3 = {
    locationNm: "Tarkibiy tuzulma",
    g33:"TIF TN kodi",
    userNm:"Xodim",
    keyword:"Ishlatilgan kalit so'zi",
    resultCount:"Topilgan qaydlar soni",
    insTime:"Izlash vaqti",
    all : "Xammasi"
}

var appTableV1Setting = {
    availableTitle: "Tanlanmagan",
    selectedTitle: "Tanlangan",
    searchPlaceholder: "Izlash",
    columnSettingNames: "Ustun sozlamasi nomi",
    settingsList: "Sozlamalar ro'yxati",
    saveSetting: "Saqlash",
    activeSetting: "Faollashtirish",
    deleteSetting: "O'chirish",
    tourBtnText: "O'chirish",
}