var appTableV1 = {
    ugtk: "Код УГТК",
    g7A: "Код Поста",
    g7B: "Дата Рег.",
    g7C: "Рег. №",
    g7Ag7Bg7C: "Номер ГТД",
    g1A: "Напр. Тов-В ",
    g1B: "Код Режима",
    g1Ag1B: "Режим",
    g32: "№ Тов.",
    g37B: "Код.Пред. Реж.",
    g37C: "Особ. Пер.",
    g2Name: "Экспортер/Отправитель",
    g8Code2: "ИНН/ПИНФЛ",
    g33: "ТН ВЭД",
    g31NameNoIcon: "Грузовые.Места.И.Описание.Товара",
    g31Name: "Грузовые.Места.И.Описание.Товара"+
            "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(1)'><i class=\"fa fa-angle-double-down m-2 openerTextArea \"/></span>" +
            "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(0)'><i class=\"fa fa-angle-double-up m-2 openerTextArea \"/></span>",
    g15: "Стр. Отп.",
    g11: "Торг.Стр.",
    vidKontrakta: "Вид Конт.",
    g34: "Стр.Прсх. (34-Гр)",
    s34: "Стр.Прсх. (31-Гр)",
    g25: "Тр.На Гран.",
    g20A: "Код.Усл. Пос",
    g20B: "Букв.Код Усл.Пос",
    g20Name: "Адрес Доставки",
    g20Ag20B:"Услов. доставки",
    g22A: "Вал.",
    g45: "Там. Ст.",
    g45Usd: "Там. Ст.$",
    g42: "Факт. Ст.",
    g42Usd: "Факт. Ст. $",
    indxusd: "Индк. Тс.$",
    indxusdLn: "Индк. Тс.$",
    g45Usded: "Тс.За Ед.$",
    g45UsdedLn: "Тс.За Ед.$",
    g31Marka: "Марка Тов.",
    g35: "Брутто (Кг)",
    g38: "Нетто (Кг)",
    g41: "Доп.Ед. Изм.",
    g43: "Собс.Нужд (43-Гр)",
    g31Amount: "Кол.во (31-Гр)",
    vesEd: "Вес Ед.",
    gdvipdate: "Дата Офр.",
    gc3Date: "Дата Ввоза",
    metod: "Метод Отс",
    vzaimosvyaz: "Вз-Связь",
    idn: "№.Идн Конт.",
    obl: "Обл",
    lgot20: "Льгота Пошлины",
    lgot27: "Льгота Акциза",
    lgot29: "Льгота Ндс",
    sovstavka: "Сов. Ст.",
    asosQiymat: "Основа Тс",
    ktd: "Изм. (Ктд)",
    oblYes: "да",
    oblNo: "нет",
    methodText: "метод",
    all : "Все записи"
}

var appTableV2 = {
    locationNm: "территориальное управление",
    g33:"Код ТЕН ВЭД",
    userNm:"Сотрудник",
    keyword:"Используемое ключевое слово",
    resultTime:"Среднее время, проведенное",
    resultCount:"Количество найденных записей",
    insTime:"Время поиска",
    all : "Все записи"
}

var appTableV3 = {
    locationNm: "территориальное управление",
    g33:"Код ТЕН ВЭД",
    userNm:"Сотрудник",
    keyword:"Используемое ключевое слово",
    resultCount:"Количество найденных записей",
    insTime:"Время поиска",
    all : "Все записи"
}


var appTableV1Setting = {
    availableTitle: "Не выбран",
    selectedTitle: "Выбрано",
    searchPlaceholder: "Поиск",
    columnSettingNames: "Имя настройки столбца",
    settingsList: "Список настроек",
    saveSetting: "Сохранить настройку",
    activeSetting: "Активировать настройку",
    deleteSetting: "Удалить настройку",
    tourBtnText: "Sozlama bo'yicha qo'llanma",
}