var appTableV1 = {
    ugtk: "Code dep.",
    g7A: "Code post",
    g7B: "date of registration of CCD",
    g7C: "CCD registration number",
    g1A: "direction of movement of goods",
    g1B: "Regime code",
    g32: "№ prod.",
    g37B: "previous customs Regime code",
    g37C: "features of the movement of goods",
    g2Name: "Exporter/shipper",
    g8Code2: "TIN of Exporter",
    g33: "HS code",
    g31Name: "Packages and description of goods",
    g15: "Departure country",
    g11: "Trading country",
    vidKontrakta: "Type of contract",
    g34: "Country of origin code",
    s34: "Country of origin code",
    g25: "Type of transport at the border",
    g20A: "delivery condition code",
    g20B: "letter code of delivery terms",
    g20Name: "Delivery address",
    g22A: "curr.",
    g45: "cus. val.",
    g45Usd: "cus. val. in USD",
    g42: "Inv. val.",
    g42Usd: "Inv. val. in USD",
    indxusd: "index",
    indxusdLn: "index",
    g45Usded: "unit in USD.",
    g45UsdedLn: "unit in USD.",
    g31Marka: "Trade mark ",
    g35: "Gross weight (kg)",
    g38: "Net weight (kg)",
    g41: "Add-l unit",
    g43: "own use",
    g31Amount: "amount",
    vesEd: "weight per unit",
    gdvipdate: "clearance time",
    gc3Date: "time of crossing the border",
    metod: "CVD method",
    vzaimosvyaz: "related parties",
    idn: "Contract number",
    obl: "taxable",
    lgot20: "import duty relief",
    lgot27: "excise relief",
    lgot29: "VAT relief",
    sovstavka: "aggregate rate",
    asosQiymat: "customs value basis",
    ktd: "changed",
};

var appTableV2 = {
    locationNm: "Regional customs office",
    g33:"HS code",
    userNm:"Employee",
    keyword:"Keyword used",
    resultTime:"Average time spent",
    resultCount:"Number of records found",
    insTime:"Search time"
};

var appTableV3 = {
    locationNm: "Regional customs office",
    g33:"HS code",
    userNm:"Employee",
    keyword:"Keyword used",
    resultCount:"Number of records found",
    insTime:"Search time"
}

