var appTableV1 = {
    ugtk: "HBB",
    g7A: "Post kodi",
    g7B: "BYuD roʼyxatdan oʼtgan sana",
    g7C: "BYuD roʼyxat raqami",
    g1A: "Rejim nomi",
    g1B: "Rejim kodi",
    g32: "Tov. No",
    g37B: "Avv. rej. kod",
    g37C: "Olib o‘t. xus-ti",
    g2Name: "Eksportchi/Jo‘natuvchi",
    g8Code2: "STIR/JShShIR",
    g33: "TIF TN",
    g31Name: "Yuk joylari va tovar tavsifi",
    g15: "Jo‘n. maml.",
    g11: "Sav.q.maml.",
    vidKontrakta: "Kont. turi",
    g34: "Kel. chiq. maml. (34-gr)",
    s34: "Kel. chiq. maml. (31-gr)",
    g25: "Chegar. tr.",
    g20A: "Etkazib berish sharti kodi",
    g20B: "Etkazib berish sharti nomi",
    g20Name: "Yetkazib berish manzili",
    g22A: "Val.",
    g45: "Boj. qiy.",
    g45Usd: "Boj. qiy. $",
    g42: "Fakt. qiy.",
    g42Usd: "Fakt. qiy. $",
    indxusd: "Boj. qiy. indk. $",
    indxusdLn: "Boj. qiy. indk. $",
    g45Usded: "Boj. qiy. 1 bir. $",
    g45UsdedLn: "Boj. qiy. 1 bir. $",
    g31Marka: "Tov. marka",
    g35: "Brutto (kg)",
    g38: "Netto (kg)",
    g41: "Qo‘sh. o‘lch. bir.",
    g43: "O‘z eht. (43-gr)",
    g31Amount: "Miqdor (31-gr)",
    vesEd: "1 bir. vazni",
    gdvipdate: "Rasm-n sana",
    gc3Date: "Olib kir. sana",
    metod: "Boj. qiy. usul",
    vzaimosvyaz: "O'zaro bog'l-k",
    idn: "Shartnoma IDN No",
    obl: "To'l. tort.",
    lgot20: "Boj imtiyozi",
    lgot27: "Aksiz imtiyozi",
    lgot29: "QQS imtiyozi",
    sovstavka: "Um. stav.",
    asosQiymat: "Boj. qiym. asosi",
    ktd: "Tuz. (KTD)",
};

var appTableV2 = {
    locationNm: "Tarkibiy tuzulma",
    g33:"TIF TN kodi",
    userNm:"Xodim",
    keyword:"Ishlatilgan kalit so'zi",
    resultTime:"O'rtacha vaqt sarfi",
    resultCount:"Topilgan qaydlar soni",
    insTime:"Izlash vaqti"
};

var appTableV3 = {
    locationNm: "Tarkibiy tuzulma",
    g33:"TIF TN kodi",
    userNm:"Xodim",
    keyword:"Ishlatilgan kalit so'zi",
    resultCount:"Topilgan qaydlar soni",
    insTime:"Izlash vaqti"
}

