var appTableV1 = {
    ugtk:"Code Dep.",
    g7A:"Code Post",
    g7B:"Date Reg.",
    g7C:"Reg. №",
    g7Ag7Bg7C: "CCD Number",
    g1A:"Direc. Goods",
    g1B:"Regime Code",
    g1Ag1B: "Regime",
    g32:"№ Prod.",
    g37B:"Prev. Cust.Reg.",
    g37C:"Feat. Mov.",
    g2Name:"Exporter/Shipper",
    g8Code2:"Tin Of Exporter",
    g33:"Hs Code",
    g31NameNoIcon: "Packages.And.Description.Of.Goods",
    g31Name:"Packages.And.Description.Of.Goods"+
        "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(1)'><i class=\"fa fa-angle-double-down m-2 openerTextArea \"/></span>" +
        "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(0)'><i class=\"fa fa-angle-double-up m-2 openerTextArea \"/></span>",
    g15:"Dep. Coun.",
    g11:"Trad. Coun.",
    vidKontrakta:"Type Contract",
    g34:"Coun. Orig.Code",
    s34:"Coun. Orig.Code",
    g25:"Type Trans.Border",
    g20A:"Delivery Con.Code",
    g20B:"Let.Code  Deliv.Terms",
    g20Name:"Delivery Address",
    g20Ag20B:"Delivery terms",
    g22A:"Curr.",
    g45:"Cus. Val.",
    g45Usd:"Cus. Val.$",
    g42:"Inv. Val.",
    g42Usd:"Inv.Val. In.$",
    indxusd:"Index $",
    indxusdLn:"Index $",
    g45Usded:"Unit In.$",
    g45UsdedLn:"Unit In.$",
    g31Marka:"Trade Mark ",
    g35:"Gross (Kg)",
    g38:"Net (Kg)",
    g41:"Add. Unit",
    g43:"Own Use",
    g31Amount:"Amount",
    vesEd:"Weight Unit",
    gdvipdate:"Clearance Time",
    gc3Date:"Cross. Border",
    metod:"Cvd Met.",
    vzaimosvyaz:"Rel. Part.",
    idn:"Contr. Number",
    obl:"Taxable",
    lgot20:"Imp.Duty Relief",
    lgot27:"Excise Relief",
    lgot29:"Vat Relief",
    sovstavka:"Agg. Rate",
    asosQiymat:"Cus. Val.Bas",
    ktd:"Chang.",
    oblYes: "yes",
    oblNo: "no",
    methodText: "method",
    all : "All reports"
};

var appTableV2 = {
    locationNm: "Regional customs office",
    g33:"HS code",
    userNm:"Employee",
    keyword:"Keyword used",
    resultTime:"Average time spent",
    resultCount:"Number of records found",
    insTime:"Search time",
    all : "All reports"
};

var appTableV3 = {
    locationNm: "Regional customs office",
    g33:"HS code",
    userNm:"Employee",
    keyword:"Keyword used",
    resultCount:"Number of records found",
    insTime:"Search time",
    all : "All reports"
}

var appTableV1Setting = {
    availableTitle: "Not selected",
    selectedTitle: "Selected",
    searchPlaceholder: "Search",
    columnSettingNames: "Column setting name",
    settingsList: "List of settings",
    saveSetting: "Save setting",
    activeSetting: "Activate setting",
    deleteSetting: "Delete the setting",
    tourBtnText: "Setup guide",
}