var appTableV1 = {
    ugtk: "HBB",
    g7A: "Post Kodi",
    g7B: "Byud Roʼy.Sana",
    g7C: "Byud №",
    g7Ag7Bg7C: "Byud raqami",
    g1A: "Rejim Nomi",
    g1B: "Rejim Kodi",
    g1Ag1B: "Rejim",
    g32: "Tov. No",
    g37B: "Avv.Rej. Kod",
    g37C: "Olib.O‘t. Xus.",
    g2Name: "Eksportchi/Jo‘Natuvchi",
    g8Code2: "STIR/JSHSHIR",
    g33: "TIF TN",
    g31Name: "Yuk.Joylari.Va.Tovar.Tavsifi"+
            "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(1)'><i class=\"fa fa-angle-double-down m-2 openerTextArea \"/></span>" +
            "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(0)'><i class=\"fa fa-angle-double-up m-2 openerTextArea \"/></span>",
    g15: "Jo‘n. Mam.",
    g11: "Sav.Q. Mam.",
    vidKontrakta: "Kont. Turi",
    g34: "Kel.Chiq.M. (34-Gr)",
    s34: "Kel.Chiq.M (31-Gr)",
    g25: "Chegar. Tr.",
    g20A: "Etk.Ber. Shart.Kodi",
    g20B: "Etk.Ber. Shart.Nomi",
    g20Name: "Etk.Ber. Shart.Manzili",
    g20Ag20B:"Yet.Ber. sharti",
    g22A: "Val.",
    g45: "Boj. Qiy.",
    g45Usd: "Boj. Qiy.$",
    g42: "Fakt. Qiy.",
    g42Usd: "Fakt. Qiy.$",
    indxusd: "Boj.Qiy. Indk.$",
    indxusdLn: "Boj.Qiy. Indk.$",
    g45Usded: "Boj.Qiy. 1.Bir.$",
    g45UsdedLn: "Boj.Qiy. 1.Bir.$",
    g31Marka: "Tov. Marka",
    g35: "Brutto (Kg)",
    g38: "Netto (Kg)",
    g41: "Qo‘sh.O‘lch. Bir.",
    g43: "O‘Z.Eht. (43-Gr)",
    g31Amount: "Miqdor (31-Gr)",
    vesEd: "1 Bir. Vazni",
    gdvipdate: "Rasm-N Sana",
    gc3Date: "Olib Kir.Sana",
    metod: "Boj.Qiy. Usul",
    vzaimosvyaz: "O'zaro Bog'.",
    idn: "Shart. Idn.No",
    obl: "To'l. Tor.",
    lgot20: "Boj Imtiyozi",
    lgot27: "Aksiz Imtiyozi",
    lgot29: "Qqs Imtiyozi",
    sovstavka: "Um. Stav.",
    asosQiymat: "Boj.Qiym. Asosi",
    ktd: "Tuz. (Ktd)",
    oblYes: "xa",
    oblNo: "yo'q",
    methodText: "usul"
};

var appTableV2 = {
    locationNm: "Tarkibiy tuzulma",
    g33:"TIF TN kodi",
    userNm:"Xodim",
    keyword:"Ishlatilgan kalit so'zi",
    resultTime:"O'rtacha vaqt sarfi",
    resultCount:"Topilgan qaydlar soni",
    insTime:"Izlash vaqti"
};

var appTableV3 = {
    locationNm: "Tarkibiy tuzulma",
    g33:"TIF TN kodi",
    userNm:"Xodim",
    keyword:"Ishlatilgan kalit so'zi",
    resultCount:"Topilgan qaydlar soni",
    insTime:"Izlash vaqti"
}

