var appTableV1 = {
    ugtk: "Код УТК",
    g7A: "Код поста",
    g7B: "Дата рег.",
    g7C: "Рег. №",
    g7Ag7Bg7C: "Номер ГТД",
    g1A: "Напр. тов-в ",
    g1B: "Код режима",
    g1Ag1B: "Режим",
    g32: "№ тов.",
    g37B: "Код.пред. реж.",
    g37C: "Особ. пер.",
    g2Name: "Экспортер/Отправитель",
    g8Code2: "ИНН/ПИНФЛ",
    g33: "Код ТН ВЭД",
    g31NameNoIcon: "Грузовые места и описание товара",
    g31Name: "Грузовые места и описание товара"+
            "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(1)'><i class=\"fa fa-angle-double-down m-2 openerTextArea \"/></span>" +
            "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(0)'><i class=\"fa fa-angle-double-up m-2 openerTextArea \"/></span>",
    g15: "Стр. отп.",
    g11: "Торг.стр.",
    vidKontrakta: "Конт.",
    g34: "Стр.прсх. (34-Гр)",
    s34: "Стр.прсх. (31-Гр)",
    g25: "Тр.на гран.",
    g20A: "Код.усл. пос",
    g20B: "Букв.код усл.пос",
    g20Name: "Адрес доставки",
    g20Ag20B:"Услов. доставки",
    g22A: "Вал.",
    g45: "Там. ст.",
    g45Usd: "Там. ст.$",
    g42: "Факт. ст.",
    g42Usd: "Факт. ст. $",
    indxusd: "Индк. тс.$",
    indxusdLn: "Индк. тс.$",
    g45Usded: "Тс.за ед.$",
    g45UsdedLn: "Тс.за ед.$",
    g31Marka: "Марка тов.",
    g35: "Брутто (кг)",
    g38: "Нетто (кг)",
    g41: "Доп.ед. изм.",
    g43: "Собс.нужд (43-Гр)",
    g31Amount: "Кол.во (31-Гр)",
    vesEd: "Вес ед.",
    gdvipdate: "Дата офр.",
    gc3Date: "Дата ввоза",
    metod: "Метод отс",
    vzaimosvyaz: "Вз-связь",
    idn: "№.идн конт.",
    obl: "Обл",
    lgot20: "Льгота пошлины",
    lgot27: "Льгота акциза",
    lgot29: "Льгота НДС",
    sovstavka: "Сов. ст.",
    asosQiymat: "Основа тс",
    ktd: "Изм. (КТД)",
    oblYes: "да",
    oblNo: "нет",
    methodText: "метод",
    all : "Все записи"
}

var appTableV2 = {
    locationNm: "территориальное управление",
    g33:"Код ТЕН ВЭД",
    userNm:"Сотрудник",
    keyword:"Используемое ключевое слово",
    resultTime:"Среднее время, проведенное",
    resultCount:"Количество найденных записей",
    insTime:"Время поиска",
    all : "Все записи"
}

var appTableV3 = {
    locationNm: "территориальное управление",
    g33:"Код ТЕН ВЭД",
    userNm:"Сотрудник",
    keyword:"Используемое ключевое слово",
    resultCount:"Количество найденных записей",
    insTime:"Время поиска",
    all : "Все записи"
}


var appTableV1Setting = {
    availableTitle: "Не выбран",
    selectedTitle: "Выбрано",
    searchPlaceholder: "Поиск",
    columnSettingNames: "Имя настройки столбца",
    settingsList: "Список настроек",
    saveSetting: "Сохранить настройку",
    activeSetting: "Активировать настройку",
    deleteSetting: "Удалить настройку",
    tourBtnText: "Sozlama bo'yicha qo'llanma",
}