var appTableV1 = {
    ugtk:"Code dep.",
    g7A:"Code post",
    g7B:"Date reg.",
    g7C:"Reg. №",
    g7Ag7Bg7C: "Number declaration",
    g1A:"Direc. goods",
    g1B:"Regime code",
    g1Ag1B: "Regime",
    g32:"№ prod.",
    g37B:"Prev. cust.reg.",
    g37C:"Feat. mov.",
    g2Name:"Exporter/Shipper",
    g8Code2:"Tin of exporter",
    g33:"HS Code",
    g31NameNoIcon: "Packages and description of goods",
    g31Name:"Packages and description of goods"+
        "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(1)'><i class=\"fa fa-angle-double-down m-2 openerTextArea \"/></span>" +
        "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(0)'><i class=\"fa fa-angle-double-up m-2 openerTextArea \"/></span>",
    g15:"Dep. coun.",
    g11:"Trad. coun.",
    vidKontrakta:"Type contract",
    g34:"Coun. orig.code",
    s34:"Coun. orig.code",
    g25:"Type trans.border",
    g20A:"Delivery con.code",
    g20B:"Let.code  deliv.Terms",
    g20Name:"Delivery address",
    g20Ag20B:"Delivery terms",
    g22A:"Curr.",
    g45:"Cus. val.",
    g45Usd:"Cus. val.$",
    g42:"Inv. val.",
    g42Usd:"Inv.val. In.$",
    indxusd:"Index $",
    indxusdLn:"Index $",
    g45Usded:"Unit in.$",
    g45UsdedLn:"Unit in.$",
    g31Marka:"Trade mark ",
    g35:"Gross (kg)",
    g38:"Net (kg)",
    g41:"Add. unit",
    g43:"Own use",
    g31Amount:"Amount",
    vesEd:"Weight unit",
    gdvipdate:"Clearance time",
    gc3Date:"Cross. border",
    metod:"Cvd met.",
    vzaimosvyaz:"Rel. part.",
    idn:"Contr. number",
    obl:"Taxable",
    lgot20:"Imp.Duty relief",
    lgot27:"Excise relief",
    lgot29:"VAT relief",
    sovstavka:"Agg. rate",
    asosQiymat:"Cus. val.bas",
    ktd:"Chang.",
    oblYes: "yes",
    oblNo: "no",
    methodText: "method",
    all : "All reports"
};

var appTableV2 = {
    locationNm: "Regional customs office",
    g33:"HS code",
    userNm:"Employee",
    keyword:"Keyword used",
    resultTime:"Average time spent",
    resultCount:"Number of records found",
    insTime:"Search time",
    all : "All reports"
};

var appTableV3 = {
    locationNm: "Regional customs office",
    g33:"HS code",
    userNm:"Employee",
    keyword:"Keyword used",
    resultCount:"Number of records found",
    insTime:"Search time",
    all : "All reports"
}

var appTableV1Setting = {
    availableTitle: "Not selected",
    selectedTitle: "Selected",
    searchPlaceholder: "Search",
    columnSettingNames: "Column setting name",
    settingsList: "List of settings",
    saveSetting: "Save setting",
    activeSetting: "Activate setting",
    deleteSetting: "Delete the setting",
    tourBtnText: "Setup guide",
}