var appTableV1 = {
     ugtk: "ҲББ",
     g7A: "Пост Коди",
     g7B: "Бюд Рўй.Cана",
     g7C: "Бюд №",
     g7Ag7Bg7C: "Бюд рақами",
     g1A: "Режим Номи",
     g1B: "Режим Коди",
     g1Ag1B: "Режим",
     g32: "Тов. №",
     g37B: "Авв.Реж. Код",
     g37C: "Олиб.Ўт. Хус-Ти",
     g2Name: "Экспортчи/Жўнатувчи",
     g20Ag20B:"Ет.Бер. шарти",
     g8Code2: "СТИР/ЖШШИР",
     g33: "ТИФ ТН",
     g31Name: "Юк.Жойлари.Ва.Товар.Тавсифи" +
         "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(1)'><i class=\"fa fa-angle-double-down m-2 openerTextArea \"/></span>" +
         "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(0)'><i class=\"fa fa-angle-double-up m-2 openerTextArea \"/></span>",
     g15: "Жўн. Мамл.",
     g11: "Сав.Қ Мамл.",
     vidKontrakta: "Конт. Тури",
     g34: "Кел.Чиқ.М (34-Гр)",
     s34: "Кел.Чиқ.М (31-Гр)",
     g25: "Чегар. Тр.",
     g20A: "Етк.Бер. Шарт.Коди",
     g20B: "Етк.Бер. Шарт.Номи",
     g20Name: "Етк.Бер. Шарт.Манзили",
     g22A: "Вал.",
     g45: "Бож. Қий.",
     g45Usd: "Бож. Қий.$",
     g42: "Факт. Қий.",
     g42Usd: "Факт. Қий.$",
     indxusd: "Бож.Қий. Индк.$",
     indxusdLn: "Бож.Қий. Индк.$",
     g45Usded: "Бож.Қий. 1.Бир.$",
     g45UsdedLn: "Бож.Қий. 1.Бир.$",
     g31Marka: "Тов. Марка",
     g35: "Брутто (Кг)",
     g38: "Нетто (Кг)",
     g41: "Қўш.Ўлч. Бир.",
     g43: "Ўз.Эҳт. (43-Гр)",
     g31Amount: "Миқдор (31-Гр)",
     vesEd: "1 Бир. Вазни",
     gdvipdate: "Расм. Сана",
     gc3Date: "Олиб Кир.Сана",
     metod: "Бож.Қий. Усул",
     vzaimosvyaz: "Ўзаро Боғл.",
     idn: "Шарт.Идн. №",
     obl: "Тўл.Торт.",
     lgot20: "Бож Имтиёзи",
     lgot27: "Акциз Имтиёзи",
     lgot29: "Ққс Имтиёзи",
     sovstavka: "Ум.Став.",
     asosQiymat: "Бож.Қийм. Асоси",
     ktd: "Туз. (Ктд)",
     oblYes: "ха",
     oblNo: "йўқ",
     methodText: "усул"
};

var appTableV2 = {
    locationNm: "Tаркибий тузулма",
    g33:"ТИФ ТН коди",
    userNm:"Ходим",
    keyword:"Ишлатилган калит сўз",
    resultTime:"Ўртача вақт сарфи",
    resultCount:"Топилган қайдлар сони",
    insTime:"Излаш вақти"
}

var appTableV3 = {
    locationNm: "Tаркибий тузулма",
    g33:"ТИФ ТН коди",
    userNm:"Ходим",
    keyword:"Ишлатилган калит сўз",
    resultCount:"Топилган қайдлар сони",
    insTime:"Излаш вақти"
}
