var appTableV1 = {
     ugtk: "ҲББ",
     g7A: "Пост коди",
     g7B: "БЮД рўй.cана",
     g7C: "БЮД №",
     g7Ag7Bg7C: "БЮД рақами",
     g1A: "Режим номи",
     g1B: "Режим коди",
     g1Ag1B: "Режим",
     g32: "Тов. №",
     g37B: "Авв.реж.коди",
     g37C: "Олиб ўтиш хус.",
     g2Name: "Экспортчи/жўнатувчи",
     g20Ag20B:"Ет.бер.шарти",
     g8Code2: "СТИР/ЖШШИР",
     g33: "ТИФ ТН коди",
     g31NameNoIcon: "Юк жойлари ва товар тавсифи",
     g31Name: "Юк жойлари ва товар тавсифи" +
         "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(1)'><i class=\"fa fa-angle-double-down m-2 openerTextArea \"/></span>" +
         "<span class='border border-white rounded openerTextArea ml-2' style='cursor: pointer' onclick='openText(0)'><i class=\"fa fa-angle-double-up m-2 openerTextArea \"/></span>",
     g15: "Жўн. мамл.",
     g11: "Сав.қ мамл.",
     vidKontrakta: "Конт. мавж.",
     g34: "Кел.чиқ.м (34-гр)",
     s34: "Кел.чиқ.м (31-гр)",
     g25: "Транспорт тури",
     g20A: "Етк.бер. шарт.коди",
     g20B: "Етк.бер. шарт.номи",
     g20Name: "Етк.бер. манзили",
     g22A: "Вал.",
     g45: "Бож. қий.",
     g45Usd: "Бож. қий.$",
     g42: "Факт. қий.",
     g42Usd: "Факт. қий.$",
     indxusd: "Бож.қий. индекси $",
     indxusdLn: "Бож.қий. индекси $",
     g45Usded: "Бож.қий. 1 бир.$",
     g45UsdedLn: "Бож.қий. 1 бир.$",
     g31Marka: "Товар маркаси",
     g35: "Брутто (кг)",
     g38: "Нетто (кг)",
     g41: "Қўш.ўлч. бир.",
     g43: "Ўз.эҳт. (43-гр)",
     g31Amount: "Миқдор (31-Гр)",
     vesEd: "1 бир. вазни",
     gdvipdate: "Расм. сана",
     gc3Date: "Олиб кир.сана",
     metod: "Бож.қий.усули",
     vzaimosvyaz: "Ўзаро боғл.",
     idn: "Шарт.идн. №",
     obl: "Тўл.торт.",
     lgot20: "Бож имтиёзи",
     lgot27: "Акциз имтиёзи",
     lgot29: "ҚҚС имтиёзи",
     sovstavka: "Ум.став.",
     asosQiymat: "Бож.қийм.асоси",
     ktd: "Туз. (ктд)",
     oblYes: "ха",
     oblNo: "йўқ",
     methodText: "усул",
     all : "Хаммаси"
};

var appTableV2 = {
    locationNm: "Tаркибий тузулма",
    g33:"ТИФ ТН коди",
    userNm:"Ходим",
    keyword:"Ишлатилган калит сўз",
    resultTime:"Ўртача вақт сарфи",
    resultCount:"Топилган қайдлар сони",
    insTime:"Излаш вақти",
    all : "Хаммаси"
}

var appTableV3 = {
    locationNm: "Tаркибий тузулма",
    g33:"ТИФ ТН коди",
    userNm:"Ходим",
    keyword:"Ишлатилган калит сўз",
    resultCount:"Топилган қайдлар сони",
    insTime:"Излаш вақти",
     all : "Хаммаси"
}

var appTableV1Setting = {
     availableTitle: "Танланмаган",
     selectedTitle: "Танланган",
     searchPlaceholder: "Излаш",
     columnSettingNames: "Устун созламаси номи",
     settingsList: "Созламалар рўйхати",
     saveSetting: "Сақлаш",
     activeSetting: "Фаоллаштириш",
     deleteSetting: "Ўчириш",
     tourBtnText: "Созлама бўйича қўлланма",
}